name: test
on:
  push:
    branches:
      - "**"
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install and Test
        run: |
          yarn install
          yarn lint
          yarn test
      - name: Setup Go 1.20.8
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.8'
      - name: Test Server
        run: |
          go mod tidy
          go test -v -coverprofile=cover.txt ./...
